services:
  mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Odoo connection settings
      - ODOO_URL=${ODOO_URL}
      - ODOO_DB=${ODOO_DB:-odoo}
      - ODOO_USERNAME=${ODOO_USERNAME:-admin}
      - ODOO_PASSWORD=${ODOO_PASSWORD}
      - ODOO_TIMEOUT=30
      - ODOO_VERIFY_SSL=0
      
      # Database settings
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-odoo}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-odoo}
      - PGPASSWORD=${PGPASSWORD}
      
      # API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Constructed URI
      - PG_URI=${PG_URI}
      
      # MCP settings
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - MCP_TRANSPORT=streamable-http
    volumes:
      - mcp-logs:/app/logs
    tty: true
    stdin_open: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - mcp
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  mcp-logs: